language: java

jdk:
  - oraclejdk8

# configure the Maven environment
before_install:
  - source <(curl -fsSL https://raw.github.com/daisy/maven-parents/travis/before_install)

install: mvn install -DskipTests=true -Dinvoker.skip=true -Dmaven.javadoc.skip=true -B -V

# main task, run the verify goal
script: mvn -B verify

# if the build succeeds, deploy the artifact (tests are skipped)
after_success: 
  - source <(curl -fsSL https://raw.github.com/daisy/maven-parents/travis/after_success)

before_cache:
  - source <(curl -fsSL https://raw.github.com/daisy/maven-parents/travis/before_cache)

cache:
  directories:
    - $HOME/.m2/cached-repository

# whitelist; only deploy master branch
branches:
  only:
  - master
  - develop
  - /^super\/.+$/

env:
  global:
  - secure: LsRshZ/UYNKLwm3VXQTUGtWep1AAXflnSLTwg47MsAMQPWs9yxdiaYPwcLKLLYU0+MPL5y7am/v69vkABq9bZrvM+c12n5vpuaoGFYcGnvUp/hEN2/uc10DHFkTg23bZcmoi0okbaSlZA4RcbxCkQCv2MDl83xWXzt2zP+xV4Ek=
  - secure: UdJpqtnK1dEUEIY+s+5cdAcTLXOTf8KV1gcm95l+TrQf1Zg25xjEZXHa8Fzmtb8so7sfY7sQjWlyL0puswquWXdYkSP1q1aEJwbiCmBOfELR+GIxcMIOvHdJqJKZEA2jz+CklqZjtPGY9mg191zbztl/e3mx4+mmfGZ+YM/c7MM=
