language: java
services:
  - docker
before_install:
  - source <(curl -fsSL https://raw.github.com/daisy/maven-parents/travis/before_install)
script:
  - mvn clean package -Plinux &&
    make GTAR=/bin/tar docker &&
    make check-docker
