name: DAISY Pipeline 2
collections:
  wiki:
    output: true
    permalink: /:path/
  wiki_gui:
    output: true
    permalink: /Get-Help/User-Guide/Desktop-Application/:path/
  wiki_webui:
    output: true
    permalink: /Get-Help/User-Guide/Web-Application/:path/
defaults:
  - scope: {path: "", type: wiki}
    values:
      layout: wiki
      spine: sitemap
      edit_button: wiki
  - scope: {path: "", type: wiki_gui}
    values:
      layout: wiki
      spine: sitemap
      edit_button: wiki-gui
  - scope: {path: "", type: wiki_webui}
    values:
      layout: wiki
      spine: sitemap
      edit_button: wiki-webui
markdown: kramdown
kramdown:
  parse_block_html: true
  syntax_highlighter: coderay
  syntax_highlighter_opts:
    line_numbers: false
    css: class
sass:
  sass_dir: css
baseurl: "/pipeline"
site_base: "http://daisy.github.io"
meta_file: _meta.ttl
